-- SiteVoice schema
-- Tenant isolation via unguessable workspace UUIDs in URL (?ws=...)
-- No auth: workspace_id functions like a Google Docs share link.
-- RLS intentionally off; security is the unguessable URL.

create table if not exists workspaces (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now()
);

create table if not exists jobs (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null references workspaces(id) on delete cascade,
    client_name text not null,
    description text not null,
    job_date text,
    job_time text,
    address text,
    priority text not null default 'normal',
    status text not null default 'Scheduled',
    notes jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists jobs_workspace_idx on jobs(workspace_id, created_at desc);

create table if not exists quotes (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null references workspaces(id) on delete cascade,
    client_name text not null,
    job_description text,
    address text,
    status text not null default 'draft',
    notes text,
    include_gst boolean not null default true,
    subtotal numeric(10, 2),
    gst numeric(10, 2),
    total numeric(10, 2),
    finalised_at timestamptz,
    created_at timestamptz not null default now()
);
create index if not exists quotes_workspace_idx on quotes(workspace_id, created_at desc);
create index if not exists quotes_active_idx on quotes(workspace_id) where status = 'draft';

create table if not exists quote_line_items (
    id bigint generated by default as identity primary key,
    quote_id bigint not null references quotes(id) on delete cascade,
    position int not null,
    item_name text not null,
    category text not null,
    unit_price numeric(10, 2) not null,
    quantity numeric(10, 2) not null,
    unit text not null default 'each',
    line_total numeric(10, 2) not null,
    created_at timestamptz not null default now()
);
create index if not exists quote_line_items_quote_idx on quote_line_items(quote_id, position);

-- Telemetry table for task #3 (created now so we don't need a second migration)
create table if not exists tool_call_events (
    id bigint generated by default as identity primary key,
    workspace_id uuid references workspaces(id) on delete cascade,
    turn_id uuid not null,
    rounds_used int not null,
    hit_cap boolean not null default false,
    tools_called text[] not null default '{}',
    total_latency_ms int,
    prompt_tokens int,
    completion_tokens int,
    error text,
    created_at timestamptz not null default now()
);
create index if not exists tool_call_events_workspace_idx on tool_call_events(workspace_id, created_at desc);
